//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace llbltest.EntityClasses
{
	/// <summary>Class which represents the entity 'Attachment'.</summary>
	public partial class Attachment : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Attachment"/> class.</summary>
		public Attachment() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CloudUrl field. </summary>
		public System.String? CloudUrl { get; set; }
		/// <summary>Gets or sets the EntityId field. </summary>
		public System.Int32 EntityId { get; set; }
		/// <summary>Gets or sets the EntityType field. </summary>
		public System.String? EntityType { get; set; }
		/// <summary>Gets or sets the FileName field. </summary>
		public System.String? FileName { get; set; }
		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the MimeType field. </summary>
		public System.String? MimeType { get; set; }
	}
}
