//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace llbltest.EntityClasses
{
	/// <summary>Class which represents the entity 'Owner'.</summary>
	public partial class Owner : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Owner"/> class.</summary>
		public Owner() : base()
		{
			OnCreated();
		}

		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the OwnerName field. </summary>
		public System.String? OwnerName { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Dealer.Owner - Owner.Dealers (1:1) (Model only)'</summary>
		public virtual Dealer Dealers { get; set; } = null!;
	}
}
