//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace llbltest.EntityClasses
{
	/// <summary>Class which represents the entity 'Penjualan'.</summary>
	public partial class Penjualan : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Penjualan"/> class.</summary>
		public Penjualan() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CustomerId field. </summary>
		public Nullable<System.Int32> CustomerId { get; set; }
		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the TransactionDate field. </summary>
		public Nullable<System.DateTime> TransactionDate { get; set; }
	}
}
