//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace llbltest.EntityClasses
{
	/// <summary>Class which represents the entity 'Salesman'.</summary>
	public partial class Salesman : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Salesman"/> class.</summary>
		public Salesman() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the DealerId field. </summary>
		public System.Int32 DealerId { get; set; }
		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the SalesName field. </summary>
		public System.String? SalesName { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Salesman.Dealer - Dealer.Salesmen (m:1)'</summary>
		public virtual Dealer Dealer { get; set; } = null!;
	}
}
