//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using llbltest.EntityClasses;

namespace llbltest
{
	/// <summary>Class which represents the DataContext for the project / group 'Llbltest'</summary>
	public partial class LlbltestDataContext : DbContext
	{
		partial void OnModelCreatingComplete();

		/// <summary>Constructor which accepts an already setup DbContextOptions instance</summary>
		/// <param name="options">The DbContextOptions object to use</param>
		public LlbltestDataContext(DbContextOptions<LlbltestDataContext> options) : base(options) {}
		
		/// <summary>Empty constructor which relies on OnConfiguring being overriden</summary>
		public LlbltestDataContext() : base() {}
		
		/// <inheritdoc/>
		public override int SaveChanges(bool acceptAllChangesOnSuccess)
		{
			CheckReadonlyEntities();
			return base.SaveChanges(acceptAllChangesOnSuccess);
		}

		/// <inheritdoc/>
		public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken())
		{
			CheckReadonlyEntities();
			return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
		}
		
		/// <inheritdoc/>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			new LlbltestModelBuilder().BuildModel(modelBuilder);
			OnModelCreatingComplete();
		}

		private void CheckReadonlyEntities()
		{
			var namesOfChangedReadOnlyEntities = this.ChangeTracker.Entries().Where(e => e.Metadata.IsReadOnly() && e.State != EntityState.Unchanged).Select(e => e.Metadata.Name).Distinct().ToList();
			if(namesOfChangedReadOnlyEntities.Any())
			{
				throw new InvalidOperationException($"Attempted to save the following read-only entitie(s): {string.Join(",", namesOfChangedReadOnlyEntities)}");
			}
		}

		/// <summary>Gets an object query for the entity set 'Dealer', containing entity type 'Dealer'</summary>
		public DbSet<Dealer> Dealers { get; set; } 
		/// <summary>Gets an object query for the entity set 'Owner', containing entity type 'Owner'</summary>
		public DbSet<Owner> Owners { get; set; } 
		/// <summary>Gets an object query for the entity set 'Penjualan', containing entity type 'Penjualan'</summary>
		public DbSet<Penjualan> Penjualans { get; set; } 
		/// <summary>Gets an object query for the entity set 'Salesman', containing entity type 'Salesman'</summary>
		public DbSet<Salesman> Salesmen { get; set; } 
	}
}
